-- AlterTable
ALTER TABLE `reservation_activities` MODIFY `name` ENUM('HOLD', 'ISSUE_REQUESTED', 'CANCEL_REQUESTED', 'TIME_REQUESTED', 'EXPIRED', 'TICKETED', 'CANCELLED', 'REFUNDED', 'VOIDED', 'APPROVED', 'DECLINED') NOT NULL;

-- AlterTable
ALTER TABLE `reservations` MODIFY `status` ENUM('HOLD', 'ISSUE_REQUESTED', 'CANCEL_REQUESTED', 'TIME_REQUESTED', 'EXPIRED', 'TICKETED', 'CANCELLED', 'REFUNDED', 'VOIDED', 'APPROVED', 'DECLINED') NOT NULL DEFAULT 'HOLD';
