-- AlterTable
ALTER TABLE `reservation_activities` MODIFY `name` ENUM('HOLD', 'ISSUE_REQUESTED', 'CANCEL_REQUESTED', 'EXPIRED', 'TICKETED', 'CANCELLED', 'REFUNDED', 'VOIDED') NOT NULL;

-- AlterTable
ALTER TABLE `reservations` MODIFY `status` ENUM('HOLD', 'ISSUE_REQUESTED', 'CANCEL_REQUESTED', 'EXPIRED', 'TICKETED', 'CANCELLED', 'REFUNDED', 'VOIDED') NOT NULL DEFAULT 'HOLD';
