-- AlterTable
ALTER TABLE `journals` MODIFY `type` ENUM('CASH_DEPOSIT', 'BANK_DEPOSIT', 'BANK_TRANSFER', 'TICKET', 'MANUAL_TICKET', 'MANUAL_CREDIT', 'DATE_CHANGED', 'REFUNDED', 'ADM', 'ACM') NOT NULL;
