-- AlterTable
ALTER TABLE `companies` ADD COLUMN `balanceStatus` ENUM('FRIDGED', 'FREEZE', 'ACTIVE') NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN `status` ENUM('WAITING', 'ENABLE', 'DISABLE') NOT NULL DEFAULT 'WAITING';
